name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Intentionally fail the check run for pull requests
      - name: Fail Check Run for Pull Requests
        if: github.event_name == 'pull_request'
        run: |
          echo "Failing check run for pull request"
          exit 1

